#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rsa
Version  : 3.4.2
Release  : 47
URL      : http://pypi.debian.net/rsa/rsa-3.4.2.tar.gz
Source0  : http://pypi.debian.net/rsa/rsa-3.4.2.tar.gz
Summary  : Pure-Python RSA implementation
Group    : Development/Tools
License  : Apache-2.0
Requires: rsa-bin = %{version}-%{release}
Requires: rsa-license = %{version}-%{release}
Requires: rsa-python = %{version}-%{release}
Requires: rsa-python3 = %{version}-%{release}
Requires: pyasn1
BuildRequires : buildreq-distutils3
BuildRequires : pyasn1

%description
Pure Python RSA implementation
==============================
[![PyPI](https://img.shields.io/pypi/v/rsa.svg)](https://pypi.python.org/pypi/rsa)
[![Build Status](https://travis-ci.org/sybrenstuvel/python-rsa.svg?branch=master)]
(https://travis-ci.org/sybrenstuvel/python-rsa)
[![Coverage Status](https://coveralls.io/repos/github/sybrenstuvel/python-rsa/badge.svg?branch=master)]
(https://coveralls.io/github/sybrenstuvel/python-rsa?branch=master)
[![Code Climate](https://img.shields.io/codeclimate/github/sybrenstuvel/python-rsa.svg)]
(https://codeclimate.com/github/sybrenstuvel/python-rsa)

%package bin
Summary: bin components for the rsa package.
Group: Binaries
Requires: rsa-license = %{version}-%{release}

%description bin
bin components for the rsa package.


%package license
Summary: license components for the rsa package.
Group: Default

%description license
license components for the rsa package.


%package python
Summary: python components for the rsa package.
Group: Default
Requires: rsa-python3 = %{version}-%{release}

%description python
python components for the rsa package.


%package python3
Summary: python3 components for the rsa package.
Group: Default
Requires: python3-core
Provides: pypi(rsa)

%description python3
python3 components for the rsa package.


%prep
%setup -q -n rsa-3.4.2
cd %{_builddir}/rsa-3.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583221053
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rsa
cp %{_builddir}/rsa-3.4.2/LICENSE %{buildroot}/usr/share/package-licenses/rsa/a4466bfd6f8b645aebdf508c1b7ede0bc018f694
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyrsa-decrypt
/usr/bin/pyrsa-decrypt-bigfile
/usr/bin/pyrsa-encrypt
/usr/bin/pyrsa-encrypt-bigfile
/usr/bin/pyrsa-keygen
/usr/bin/pyrsa-priv2pub
/usr/bin/pyrsa-sign
/usr/bin/pyrsa-verify

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rsa/a4466bfd6f8b645aebdf508c1b7ede0bc018f694

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
