#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rsa
Version  : 3.4.2
Release  : 17
URL      : https://pypi.python.org/packages/source/r/rsa/rsa-3.4.2.tar.gz
Source0  : https://pypi.python.org/packages/source/r/rsa/rsa-3.4.2.tar.gz
Summary  : Pure-Python RSA implementation
Group    : Development/Tools
License  : Apache-2.0
Requires: rsa-bin
Requires: rsa-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pyasn1
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Pure Python RSA implementation
==============================
[![PyPI](https://img.shields.io/pypi/v/rsa.svg)](https://pypi.python.org/pypi/rsa)
[![Build Status](https://travis-ci.org/sybrenstuvel/python-rsa.svg?branch=master)]
(https://travis-ci.org/sybrenstuvel/python-rsa)
[![Coverage Status](https://coveralls.io/repos/github/sybrenstuvel/python-rsa/badge.svg?branch=master)]
(https://coveralls.io/github/sybrenstuvel/python-rsa?branch=master)
[![Code Climate](https://img.shields.io/codeclimate/github/sybrenstuvel/python-rsa.svg)]
(https://codeclimate.com/github/sybrenstuvel/python-rsa)

%package bin
Summary: bin components for the rsa package.
Group: Binaries

%description bin
bin components for the rsa package.


%package python
Summary: python components for the rsa package.
Group: Default

%description python
python components for the rsa package.


%prep
%setup -q -n rsa-3.4.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyrsa-decrypt
/usr/bin/pyrsa-decrypt-bigfile
/usr/bin/pyrsa-encrypt
/usr/bin/pyrsa-encrypt-bigfile
/usr/bin/pyrsa-keygen
/usr/bin/pyrsa-priv2pub
/usr/bin/pyrsa-sign
/usr/bin/pyrsa-verify

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
