#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rsa
Version  : 3.4
Release  : 16
URL      : https://pypi.python.org/packages/source/r/rsa/rsa-3.4.tar.gz
Source0  : https://pypi.python.org/packages/source/r/rsa/rsa-3.4.tar.gz
Summary  : Pure-Python RSA implementation
Group    : Development/Tools
License  : Apache-2.0
Requires: rsa-bin
Requires: rsa-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pyasn1
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
No detailed description available

%package bin
Summary: bin components for the rsa package.
Group: Binaries

%description bin
bin components for the rsa package.


%package python
Summary: python components for the rsa package.
Group: Default

%description python
python components for the rsa package.


%prep
%setup -q -n rsa-3.4

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyrsa-decrypt
/usr/bin/pyrsa-decrypt-bigfile
/usr/bin/pyrsa-encrypt
/usr/bin/pyrsa-encrypt-bigfile
/usr/bin/pyrsa-keygen
/usr/bin/pyrsa-priv2pub
/usr/bin/pyrsa-sign
/usr/bin/pyrsa-verify

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
